services:
  - type: web
    name: quantstack
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run QuantStack-main/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: $PORT