"""Browser interaction checks against a running dashboard (uses Microsoft Edge)."""
from pathlib import Path
import argparse
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://127.0.0.1:8765')
args = parser.parse_args()

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel='msedge', headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1100}, device_scale_factor=1)
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(args.url)
    expect(page.locator('#symbol')).to_have_text('AAPL')
    expect(page.locator('#rows tr')).to_have_count(15)
    page.locator('#usageButton').click()
    expect(page.locator('#usageDialog')).to_be_visible()
    expect(page.locator('#usageRows tr')).to_have_count(5)
    expect(page.locator('#usageSummary')).to_contain_text('REQUESTS / 24H')
    page.locator('#doneUsage').click()
    page.locator('#indicatorLibrary').click()
    expect(page.locator('#indicatorDialog')).to_be_visible()
    page.wait_for_function("Number(document.getElementById('indicatorCount').textContent) >= 178")
    for indicator in ('RSI', 'MACD', 'SAR', 'CDLDOJI'):
        page.locator('#indicatorSearch').fill(indicator)
        page.locator(f'[data-advanced="{indicator}"]').click()
        expect(page.locator(f'[data-advanced="{indicator}"]')).to_have_class('indicator-item active')
    page.locator('#closeIndicators').click()
    expect(page.locator('.indicator-panel')).to_have_count(3)
    page.screenshot(path='data/dashboard-desktop.png', full_page=True)
    page.locator('#search').fill('microsoft')
    expect(page.locator('.asset')).to_have_count(1)
    page.locator('.asset').click()
    expect(page.locator('#symbol')).to_have_text('MSFT')
    expect(page.locator('#rows tr')).to_have_count(15)
    page.locator('#save').click()
    page.locator('#search').fill('')
    page.locator('[data-filter="Saved"]').click()
    expect(page.locator('.asset')).to_have_count(1)
    page.get_by_role('button', name='Crypto', exact=True).click()
    expect(page.locator('.asset')).to_have_count(2)
    page.locator('[data-symbol="BTC-USD"]').click()
    expect(page.locator('#symbol')).to_have_text('BTC-USD')
    page.locator('[data-interval="1h"]').click()
    page.locator('[data-period="MAX"]').click()
    expect(page.locator('#rangeSummary')).to_contain_text('1h bars')
    assert int(page.locator('#records').inner_text().replace(',', '')) > 7_000
    page.locator('[data-interval="1d"]').click()
    page.locator('#start').fill('2025-01-01')
    page.locator('#end').fill('2025-01-31')
    page.locator('#apply').click()
    expect(page.locator('#records')).to_have_text('31')
    page.locator('[data-type="line"]').click()
    expect(page.locator('[data-type="line"]')).to_have_class('active')
    page.locator('[data-type="candles"]').click()
    for indicator in ('sma', 'ema', 'bb', 'volume'):
        page.locator(f'[data-indicator="{indicator}"]').click()
        expect(page.locator(f'[data-indicator="{indicator}"]')).to_have_class('active')
    chart = page.locator('#chart')
    bounds = chart.bounding_box()
    page.mouse.move(bounds['x'] + bounds['width'] * .65, bounds['y'] + bounds['height'] * .4)
    page.screenshot(path='data/dashboard-crosshair.png')
    page.locator('[data-tool="trend"]').click()
    page.mouse.click(bounds['x'] + bounds['width'] * .3, bounds['y'] + bounds['height'] * .65)
    page.mouse.click(bounds['x'] + bounds['width'] * .6, bounds['y'] + bounds['height'] * .4, button='right')
    expect(page.locator('[data-tool="cursor"]')).to_have_class('active')
    two_point_tools = ('trend', 'ray', 'rectangle', 'fib', 'measure')
    for index, drawing_tool in enumerate(two_point_tools, 1):
        page.locator(f'[data-tool="{drawing_tool}"]').click()
        page.mouse.click(bounds['x'] + bounds['width'] * .3, bounds['y'] + bounds['height'] * .65)
        page.mouse.move(bounds['x'] + bounds['width'] * .7, bounds['y'] + bounds['height'] * .3)
        if drawing_tool == 'trend':
            page.screenshot(path='data/dashboard-drawing-preview.png')
        page.mouse.click(bounds['x'] + bounds['width'] * .7, bounds['y'] + bounds['height'] * .3)
        assert page.evaluate("JSON.parse(localStorage.getItem('atlas.drawings.BTC-USD.1d')).length") == index
    page.locator('[data-tool="vertical"]').click()
    page.mouse.click(bounds['x'] + bounds['width'] * .55, bounds['y'] + bounds['height'] * .5)
    page.locator('[data-tool="horizontal"]').click()
    page.mouse.click(bounds['x'] + bounds['width'] * .5, bounds['y'] + bounds['height'] * .5)
    assert page.evaluate("JSON.parse(localStorage.getItem('atlas.drawings.BTC-USD.1d')).length") == 7
    page.locator('#undoDrawing').click()
    page.locator('#next').click()
    expect(page.locator('#pageInfo')).to_contain_text('16–30')
    with page.expect_download() as download:
        page.locator('#download').click()
    path = download.value.path()
    assert len(Path(path).read_text().splitlines()) == 32
    page.locator('#start').fill('2025-02-01')
    page.locator('#apply').click()
    expect(page.locator('#error')).to_be_visible()
    page.locator('#start').fill('1900-01-01')
    page.locator('#end').fill('1900-01-02')
    page.locator('#apply').click()
    expect(page.locator('#records')).to_have_text('0')
    expect(page.locator('#download')).to_be_disabled()
    page.locator('[data-period="1Y"]').click()
    expect(page.locator('#rows tr')).to_have_count(15)
    page.set_viewport_size({'width':390, 'height':844})
    page.screenshot(path='data/dashboard-mobile.png', full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile layout overflow'
    assert not errors, errors
    browser.close()
    print('PASS: search, candles/line, drawings, favorites, dates, pagination, export, empty/error states, mobile layout; no JavaScript errors.')
