const $=id=>document.getElementById(id),fmt=(n,d=2)=>n==null?'—':Number(n).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}),pct=n=>n==null?'—':`${n>=0?'+':''}${fmt(n)}%`;
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
let saved;try{saved=new Set(JSON.parse(localStorage.getItem('atlas.saved')||'[]'))}catch{saved=new Set()}
let assets=[],selected=null,filter='All',period='1Y',interval='1d',chartType='candles',tool='cursor',magnet=true,indicators=new Set(),advancedCatalog=[],advanced=new Map(),rows=[],page=0,generation=0,viewStart=0,viewCount=0,hover=-1,hoverY=null,hoverAnchor=null,drag=null,pending=null,drawings=[];
const indicatorColors=['#f5c451','#4c8dff','#a879ff','#26a69a','#ef5350','#e879f9'];
async function api(url){if(window.atlasApi)return window.atlasApi(url);const r=await fetch('.'+url),data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load data');return data}
function showError(message=''){$('error').textContent=message;$('error').hidden=!message}
async function loadUsage(){const button=$('refreshUsage');button.disabled=true;$('usageRows').innerHTML='<tr><td colspan="6">Loading request activity…</td></tr>';try{const data=await api('/api/usage'),providers=data.providers,totalRequests=providers.reduce((n,p)=>n+p.requests,0),totalRows=providers.reduce((n,p)=>n+p.rows,0),failures=providers.reduce((n,p)=>n+p.failures,0);$('usageSummary').innerHTML=`<div><span>REQUESTS / 24H</span><strong>${fmt(totalRequests,0)}</strong></div><div><span>ROWS RETURNED / 24H</span><strong>${fmt(totalRows,0)}</strong></div><div><span>FAILURES / 24H</span><strong class="${failures?'negative':'positive'}">${fmt(failures,0)}</strong></div>`;$('usageRows').innerHTML=providers.map(p=>`<tr><td><strong>${esc(p.provider)}</strong><small>${esc(p.access)}</small></td><td>${fmt(p.requests,0)}</td><td>${fmt(p.rows,0)}</td><td>${fmt(p.failures,0)}</td><td>${p.last_request?esc(labelTime(p.last_request)):'—'}</td><td class="status-${p.status||''}">${p.status?esc(p.status):'No activity'}</td></tr>`).join('');$('usageLimits').innerHTML=providers.map(p=>`<div class="usage-limit"><strong>${esc(p.provider)}</strong><span>${esc(p.candle_limit)}</span></div>`).join('')}catch(e){$('usageRows').innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`}finally{button.disabled=false}}
let watchlistLimit=100,watchlistQuery="";
function renderAssets(){
 const q=$('search').value.trim().toLowerCase(),lists=window.quantWatchlists;
 const filtered=assets.filter(a=>(filter==='All'||filter===a.kind||filter==='Saved'&&saved.has(a.symbol))&&(!lists||lists.accepts(a.symbol))&&`${a.symbol} ${a.name}`.toLowerCase().includes(q));
 const visible=lists?.sort?lists.sort(filtered):filtered;
 const signature=filter+'|'+q+'|'+(lists?.signature()||'');
 if(signature!==watchlistQuery){watchlistLimit=100;watchlistQuery=signature;$('assets').scrollTop=0}
 $('count').textContent=`${visible.length} ASSETS`;
 $('assets').innerHTML=(lists?.header?.()||'')+(visible.slice(0,watchlistLimit).map(a=>{
   const html=lists?.content?lists.content(a):`<button class="asset ${a.symbol===selected?.symbol?'active':''}" data-symbol="${esc(a.symbol)}"><span class="mini-icon">${esc(a.symbol.slice(0,2))}</span><span class="asset-info"><strong>${esc(a.symbol)}${saved.has(a.symbol)?' \u2605':''}</strong><small>${esc(a.name)}</small></span><span class="asset-price">${fmt(a.close)}<small class="${a.change>=0?'positive':'negative'}">${pct(a.change)}</small></span></button>`;
   return lists?lists.row(a.symbol,html):html;
 }).join('')||'<div class="no-results">No matching instruments. Use + Add symbol to edit your watchlist, or change the search and label filters.</div>');
 if(visible.length>watchlistLimit){const more=document.createElement('button');more.id='watchlistMore';more.className='watchlist-more';more.textContent=`Show next ${Math.min(100,visible.length-watchlistLimit)} of ${visible.length} assets`;more.onclick=()=>{const scroll=$('assets').scrollTop;watchlistLimit+=100;renderAssets();$('assets').scrollTop=scroll;$('watchlistMore')?.focus({preventScroll:true})};$('assets').append(more)}
}
function setDates(){const end=['1d','1w','1mo'].includes(interval)&&selected.date?selected.date:new Date().toISOString().slice(0,10),start=new Date(end+'T12:00:00Z');if(period==='1D')start.setUTCDate(start.getUTCDate()-1);if(period==='5D')start.setUTCDate(start.getUTCDate()-5);if(period==='1M')start.setUTCMonth(start.getUTCMonth()-1);if(period==='6M')start.setUTCMonth(start.getUTCMonth()-6);if(period==='1Y')start.setUTCFullYear(start.getUTCFullYear()-1);if(period==='5Y')start.setUTCFullYear(start.getUTCFullYear()-5);$('end').value=end;$('start').value=period==='MAX'?'':start.toISOString().slice(0,10)}
function updateSaved(){const yes=saved.has(selected.symbol);$('save').textContent=yes?'★ Saved':'☆ Save';$('save').setAttribute('aria-pressed',yes)}
async function select(symbol){selected=assets.find(a=>a.symbol===symbol);if(!selected)return;if(selected.has_daily===false){interval=selected.quote_interval||'1h';period='1Y';[...$('intervals').children].forEach(b=>b.classList.toggle('active',b.dataset.interval===interval));[...$('periods').children].forEach(b=>b.classList.toggle('active',b.dataset.period===period))}$('symbol').textContent=selected.symbol;$('name').textContent=selected.name;$('assetIcon').textContent=selected.symbol.slice(0,2);$('exchange').textContent=selected.exchange||selected.kind;$('price').textContent=fmt(selected.close);$('currency').textContent=selected.currency||'';const minute=['1m','5m','15m','1h'].includes(selected.quote_interval);$('change').textContent=`${pct(selected.change)} ${selected.has_daily===false?'daily comparison unavailable':minute?'vs last daily close':'daily'}`;$('change').className='change '+(selected.change>=0?'positive':'negative');$('asof').textContent=selected.has_data===false?'No price history available in this dataset':`${minute?`Latest stored ${selected.quote_interval==='1h'?'1-hour':selected.quote_interval.replace('m','-minute')} close`:'Daily close'} as of ${labelTime(selected.quote_timestamp||selected.date)} · Yahoo Finance`;$('chartTitle').textContent=`${selected.symbol} chart`;updateSaved();renderAssets();if(period!=='CUSTOM')setDates();loadDrawings();await loadHistory()}
function query(){const q=new URLSearchParams({symbol:selected.symbol,interval});if($('start').value)q.set('start',$('start').value);if($('end').value)q.set('end',$('end').value);return q}
async function loadHistory(){finishStyleEdit();cancelDrawingGesture();pending=null;hover=-1;hoverY=null;hoverAnchor=null;const token=++generation;showError();rows=[];render();$('rangeSummary').textContent='Loading price bars…';try{const result=await api('/api/history?'+query());if(token!==generation)return;rows=result;page=0;viewCount=Math.min(rows.length,interval==='1d'?260:300);viewStart=Math.max(0,rows.length-viewCount);await reloadLiquidations();await reloadAdvanced();if(token!==generation)return;render()}catch(e){if(token===generation){showError(e.message);$('rangeSummary').textContent='Could not load this range.'}}}
function visible(){return rows.slice(viewStart,viewStart+viewCount)}
function render(){const first=rows[0]?.close,last=rows.at(-1)?.close,change=first?(last/first-1)*100:null,coverage=rows.at(-1)?.sources?` · ${rows.at(-1).sources}-source composite`:'';$('return').textContent=pct(change);$('return').className=change==null?'':change>=0?'positive':'negative';$('high').textContent=rows.length?fmt(Math.max(...rows.map(r=>r.high))):'—';$('low').textContent=rows.length?fmt(Math.min(...rows.map(r=>r.low))):'—';$('records').textContent=fmt(rows.length,0);$('rangeSummary').textContent=rows.length?`${labelTime(rows[0].date)} — ${labelTime(rows.at(-1).date)} · ${fmt(rows.length,0)} ${interval} bars${coverage}`:'No bars in this range';const active=[...indicators].map(x=>indicatorLabel(x)).concat([...advanced.keys()]).join(' · ');$('legend').textContent=`${interval} ${chartType}${active?' · '+active:''}${coverage}`;$('download').disabled=!rows.length;$('chartEmpty').textContent=selected?.has_data===false?'No price history available in this dataset.':'No price bars in this range.';$('chartEmpty').hidden=!!rows.length;renderTable();draw()}
function labelTime(value){if(!value)return'';if(value.length===10)return value;const d=new Date(value);return d.toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function renderTable(){const total=Math.ceil(rows.length/15);page=Math.max(0,Math.min(page,Math.max(0,total-1)));const part=rows.slice().reverse().slice(page*15,page*15+15);$('rows').innerHTML=part.map(r=>`<tr><td>${esc(labelTime(r.date))}</td>${['open','high','low','close','adjusted_close'].map(k=>`<td>${fmt(r[k])}</td>`).join('')}<td>${fmt(r.volume,0)}</td><td>${esc(r.source||'Yahoo Finance')}</td></tr>`).join('')||'<tr><td colspan="8">No bars available.</td></tr>';$('pageInfo').textContent=rows.length?`${page*15+1}–${Math.min((page+1)*15,rows.length)} of ${fmt(rows.length,0)}`:'0 bars';$('prev').disabled=page===0;$('next').disabled=page+1>=total}
function geometry(){const canvas=$('chart'),box=canvas.getBoundingClientRect(),data=visible(),w=box.width,h=box.height,left=10,right=72,top=18,bottom=30,pw=w-left-right,ph=h-top-bottom;let min=data.length?Math.min(...data.map(r=>r.low)):0,max=data.length?Math.max(...data.map(r=>r.high)):1,span=max-min||Math.abs(max)*.02||1;min-=span*.08;max+=span*.08;span=max-min;return{canvas,box,data,w,h,left,right,top,bottom,pw,ph,min,max,span,x:i=>left+(i+.5)/Math.max(1,data.length)*pw,y:v=>top+(max-v)/span*ph,price:y=>max-(y-top)/ph*span}}
function plotSeries(c,g,series,color,width=1.5,dash=[]){c.beginPath();let started=false;g.data.forEach((_,i)=>{const value=series[viewStart+i],py=value==null?NaN:g.y(value);if(!Number.isFinite(value)||!Number.isFinite(py)){started=false;return}started?c.lineTo(g.x(i),py):c.moveTo(g.x(i),py);started=true});c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.stroke();c.setLineDash([])}
function draw(){const g=geometry(),{canvas,box,data,w,h,left,right,top,bottom,pw,ph,min,max,span,x,y}=g,dpr=devicePixelRatio||1;canvas.width=Math.max(1,box.width*dpr);canvas.height=Math.max(1,box.height*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#111722';c.fillRect(0,0,w,h);if(!data.length||pw<=0)return;c.font='10px Segoe UI';c.lineWidth=1;for(let i=0;i<6;i++){const py=top+i*ph/5;c.strokeStyle='#273142';c.beginPath();c.moveTo(left,py);c.lineTo(w-right+5,py);c.stroke();c.fillStyle='#8b98aa';c.textAlign='left';c.fillText(fmt(max-i*span/5,max>1000?0:2),w-right+11,py+3)}
 if(indicators.has('volume'))drawVolume(c,g);if(chartType==='candles'){const cw=Math.max(1,Math.min(12,pw/data.length*.68));data.forEach((r,i)=>{const px=x(i),up=r.close>=r.open,color=up?'#26a69a':'#ef5350';c.strokeStyle=color;c.fillStyle=color;c.beginPath();c.moveTo(px,y(r.high));c.lineTo(px,y(r.low));c.stroke();const oy=y(r.open),cy=y(r.close),bh=Math.max(1,Math.abs(cy-oy));c.fillRect(px-cw/2,Math.min(oy,cy),cw,bh)})}else{const grad=c.createLinearGradient(0,top,0,h-bottom);grad.addColorStop(0,'rgba(41,121,255,.25)');grad.addColorStop(1,'rgba(41,121,255,0)');c.beginPath();data.forEach((r,i)=>i?c.lineTo(x(i),y(r.close)):c.moveTo(x(i),y(r.close)));c.lineTo(x(data.length-1),h-bottom);c.lineTo(left,h-bottom);c.closePath();c.fillStyle=grad;c.fill();c.beginPath();data.forEach((r,i)=>i?c.lineTo(x(i),y(r.close)):c.moveTo(x(i),y(r.close)));c.strokeStyle='#4c8dff';c.lineWidth=2;c.stroke()}drawIndicators(c,g);
 const ticks=w<600?3:6;for(let i=0;i<ticks;i++){const ix=Math.min(data.length-1,Math.round(i*(data.length-1)/Math.max(1,ticks-1)));c.fillStyle='#8b98aa';c.textAlign=i===0?'left':i===ticks-1?'right':'center';c.fillText(labelTime(data[ix].date),x(ix),h-7)}c.textAlign='left';drawAnnotations(c,g);
 if(hover>=0&&hover<data.length&&hoverY!=null){const px=x(hover),py=Math.max(top,Math.min(h-bottom,hoverY)),r=data[hover],crossPrice=hoverAnchor?.price??g.price(py);c.setLineDash([3,4]);c.strokeStyle=tool==='cursor'?'#718096':'#9a8150';c.beginPath();c.moveTo(px,top);c.lineTo(px,h-bottom);c.moveTo(left,py);c.lineTo(w-right+5,py);c.stroke();c.setLineDash([]);c.fillStyle='#344258';c.fillRect(w-right+5,py-10,right-5,20);c.fillRect(Math.max(left,px-66),h-bottom,132,bottom);c.fillStyle='#f1f5f9';c.textAlign='left';c.fillText(fmt(crossPrice,crossPrice>1000?0:2),w-right+10,py+4);c.textAlign='center';c.fillText(labelTime(r.date),Math.max(left+66,Math.min(w-right-66,px)),h-9);if(tool!=='cursor'){c.fillStyle='#f5c451';c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fill();if(hoverAnchor?.snap){c.textAlign='left';c.fillText(hoverAnchor.snap,px+7,py-7)}}c.textAlign='left'}drawAdvancedPanels() }
$('assets').onclick=e=>{const b=e.target.closest('[data-symbol]');if(b)select(b.dataset.symbol)};$('search').oninput=renderAssets;$('filters').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;[...$('filters').children].forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderAssets()};
$('intervals').onclick=e=>{if(!e.target.dataset.interval||!selected)return;interval=e.target.dataset.interval;period=({'1d':'1Y','1h':'5D','1w':'5Y','1mo':'MAX'})[interval];[...$('intervals').children].forEach(b=>b.classList.toggle('active',b.dataset.interval===interval));[...$('periods').children].forEach(b=>b.classList.toggle('active',b.dataset.period===period));setDates();loadDrawings();loadHistory()};
$('chartTypes').onclick=e=>{if(!e.target.dataset.type)return;chartType=e.target.dataset.type;[...$('chartTypes').children].forEach(b=>b.classList.toggle('active',b.dataset.type===chartType));render()};
$('periods').onclick=e=>{if(!e.target.dataset.period||!selected)return;period=e.target.dataset.period;[...$('periods').children].forEach(b=>b.classList.toggle('active',b.dataset.period===period));setDates();loadHistory()};$('apply').onclick=()=>{if(!selected)return;if($('start').value&&$('end').value&&$('start').value>$('end').value){showError('Start date must be before the end date.');return}period='CUSTOM';[...$('periods').children].forEach(b=>b.classList.remove('active'));loadHistory()};
$('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('save').onclick=()=>{if(!selected)return;saved.has(selected.symbol)?saved.delete(selected.symbol):saved.add(selected.symbol);localStorage.setItem('atlas.saved',JSON.stringify([...saved]));updateSaved();renderAssets()};$('download').onclick=()=>{if(!selected)return;if(!window.ATLAS_STATIC){location.href='./api/export?'+query();return}const fields=['date','open','high','low','close','adjusted_close','volume','dividends','splits'];const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"';const csv=[['symbol',...fields].join(','),...rows.map(row=>[selected.symbol,...fields.map(field=>row[field])].map(quote).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=selected.symbol.replace(/[^a-zA-Z0-9._-]/g,'_')+'-prices.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('usageButton').onclick=()=>{$('usageDialog').showModal();loadUsage()};$('closeUsage').onclick=$('doneUsage').onclick=()=>$('usageDialog').close();$('refreshUsage').onclick=loadUsage;$('usageDialog').onclick=e=>{if(e.target===$('usageDialog'))$('usageDialog').close()};
async function init(){try{showError();$('refresh').disabled=true;if(window.ATLAS_STATIC){[...$('intervals').querySelectorAll('[data-interval="1h"]')].forEach(b=>{b.disabled=true;b.title='Hourly charts are available on the local dashboard'});document.querySelector('[data-indicator="liquidations"]').disabled=true;document.querySelector('[data-indicator="liquidations"]').title='Live liquidation capture is available on the local dashboard';document.querySelector('.live-badge').textContent='Daily hosted snapshot';$('usageButton').disabled=true;$('usageButton').title='API usage is available on the local dashboard';$('indicatorLibrary').disabled=true;$('indicatorLibrary').title='The full TA library is available on the local dashboard'}assets=await api('/api/symbols');$('libraryCount').textContent=`· ${assets.length}`;renderAssets();if(assets.length){const preferred=window.restoreChartSession?.()||selected?.symbol;await select(assets.some(a=>a.symbol===preferred)?preferred:assets.some(a=>a.symbol==='AAPL')?'AAPL':assets[0].symbol);}else{$('rangeSummary').textContent='No stored market data yet';$('chartEmpty').hidden=false}}catch(e){showError(e.message)}finally{$('refresh').disabled=false}}$('refresh').onclick=init;
